### ISSUE TITLE
能否支持每行预览字数？

### ISSUE THREAD

**Issue by hxy493045049** [lz37/noveler#1]
感谢大佬开发这款插件。好用！

最近闲时有在写网络小说，考虑到手机端阅读时，一般每行显示40个字符，
所以我在写文的时候会做个换行限制，防止段落过长影响阅读体验。
这个vscode原生就支持, 我在setting.json 中添加了这个

`"[plaintext]": {
        "editor.wrappingIndent": "none",
        "editor.wordWrapColumn": 36,
        "editor.autoIndent": "none"
    },`

但是发现插件的预览功能还不支持设置每行最大字符，所以不知道可否考虑下这个功能？

**Comment by lz37** [comment]
这个功能目前可以配合字体大小和界面宽度来实现
你可以陈述下必要性  合理的话我会加上

**Comment by lz37** [comment]
issue长时间没有回复 先关闭了
