### ISSUE TITLE
建议作者大大添加字数实时统计功能

### ISSUE THREAD

**Issue by unstarlight** [lz37/noveler#14]
建议作者大大能添加一下单个文件的字数实时统计功能

这对于一个网文写作来说是一个很重要的功能
目前状态栏中显示的只有码字的时间与速度，而写作时需要实时能够看见自己单个章节的字数
许多码字软件都是有字数实时查看功能的，如作家助手、橙瓜码字、小黑屋等
如果已经有这个功能了，但是需要修改通过修改json配置的话，希望能将其改为常驻功能

或许可以通过多线程来实现
开启一个独立的线程，循环获取用户所打开文件的字数，然后显示在状态栏上

我真得很想帮忙贡献代码，可惜本人就是一个小小的后端程序员，对于写VScode插件这类的技术一窍不通，只能给一点业务逻辑了
希望作者大大加油

**Comment by lz37** [comment]
很抱歉没有及时更新wiki

目前的话可以在 `noveler.statusItems` 数组中添加 `"TextWordCount"` 字符串来查看字数，还可以使用插件 [`Word Count CJK`](https://marketplace.visualstudio.com/items?itemName=holmescn.vscode-wordcount-cjk)  来查看字数，这个插件显示字数信息更加的详细

**Comment by unstarlight** [comment]
知道了，谢谢
